#### functions for processing grid references of varying types
#### Simon Gillings
#### Created December 2013


cat('Functions for processing grid references...\n')


#####################################################################################################################################################
# convert 1km reference to 10km reference -----------------------------------------------------------------------
#####################################################################################################################################################
gridconv1km.to.10km<-function(df,invar) 
  #df = the dataframe to process
  #invar = the name of the variable holding the grid reference
  {
  invar.index<-which(names(df)== invar)
  print(invar.index)
  df$tenkm<-paste(substr(df[,invar.index],1,3),substr(df[,invar.index],5,5),sep=''  )
  return(df)
}



#####################################################################################################################################################
# convert 10km reference to 20km reference -----------------------------------------------------------------------
#####################################################################################################################################################
gridconv10km.to.20km<-function(df,invar) 
  #df = the dataframe to process
  #invar = the name of the variable holding the grid reference
{
  #which column to process
  invar.index<-which(names(df)== invar)
  #force name to be tenkm to make easier processing
  names(df)[invar.index]<-'tenkm'
  df$let<-substr(df$tenkm,1,2)
  df$east<-as.numeric(substr(df$tenkm,3,3))
  df$north<-as.numeric(substr(df$tenkm,4,4))
  df$segref<-NA
  df$segref<-ifelse(df$east==0 & df$north==0,'_A',df$segref)
  df$segref<-ifelse(df$east==0 & df$north==1,'_A',df$segref)
  df$segref<-ifelse(df$east==1 & df$north==0,'_A',df$segref)
  df$segref<-ifelse(df$east==1 & df$north==1,'_A',df$segref)
  df$segref<-ifelse(df$east==2 & df$north==0,'_F',df$segref)
  df$segref<-ifelse(df$east==2 & df$north==1,'_F',df$segref)
  df$segref<-ifelse(df$east==3 & df$north==0,'_F',df$segref)
  df$segref<-ifelse(df$east==3 & df$north==1,'_F',df$segref)
  df$segref<-ifelse(df$east==4 & df$north==0,'_K',df$segref)
  df$segref<-ifelse(df$east==4 & df$north==1,'_K',df$segref)
  df$segref<-ifelse(df$east==5 & df$north==0,'_K',df$segref)
  df$segref<-ifelse(df$east==5 & df$north==1,'_K',df$segref)
  df$segref<-ifelse(df$east==6 & df$north==0,'_Q',df$segref)
  df$segref<-ifelse(df$east==6 & df$north==1,'_Q',df$segref)
  df$segref<-ifelse(df$east==7 & df$north==0,'_Q',df$segref)
  df$segref<-ifelse(df$east==7 & df$north==1,'_Q',df$segref)
  df$segref<-ifelse(df$east==8 & df$north==0,'_V',df$segref)
  df$segref<-ifelse(df$east==8 & df$north==1,'_V',df$segref)
  df$segref<-ifelse(df$east==9 & df$north==0,'_V',df$segref)
  df$segref<-ifelse(df$east==9 & df$north==1,'_V',df$segref)
  df$segref<-ifelse(df$east==0 & df$north==2,'_B',df$segref)
  df$segref<-ifelse(df$east==0 & df$north==3,'_B',df$segref)
  df$segref<-ifelse(df$east==1 & df$north==2,'_B',df$segref)
  df$segref<-ifelse(df$east==1 & df$north==3,'_B',df$segref)
  df$segref<-ifelse(df$east==2 & df$north==2,'_G',df$segref)
  df$segref<-ifelse(df$east==2 & df$north==3,'_G',df$segref)
  df$segref<-ifelse(df$east==3 & df$north==2,'_G',df$segref)
  df$segref<-ifelse(df$east==3 & df$north==3,'_G',df$segref)
  df$segref<-ifelse(df$east==4 & df$north==2,'_L',df$segref)
  df$segref<-ifelse(df$east==4 & df$north==3,'_L',df$segref)
  df$segref<-ifelse(df$east==5 & df$north==2,'_L',df$segref)
  df$segref<-ifelse(df$east==5 & df$north==3,'_L',df$segref)
  df$segref<-ifelse(df$east==6 & df$north==2,'_R',df$segref)
  df$segref<-ifelse(df$east==6 & df$north==3,'_R',df$segref)
  df$segref<-ifelse(df$east==7 & df$north==2,'_R',df$segref)
  df$segref<-ifelse(df$east==7 & df$north==3,'_R',df$segref)
  df$segref<-ifelse(df$east==8 & df$north==2,'_W',df$segref)
  df$segref<-ifelse(df$east==8 & df$north==3,'_W',df$segref)
  df$segref<-ifelse(df$east==9 & df$north==2,'_W',df$segref)
  df$segref<-ifelse(df$east==9 & df$north==3,'_W',df$segref)
  df$segref<-ifelse(df$east==0 & df$north==4,'_C',df$segref)
  df$segref<-ifelse(df$east==0 & df$north==5,'_C',df$segref)
  df$segref<-ifelse(df$east==1 & df$north==4,'_C',df$segref)
  df$segref<-ifelse(df$east==1 & df$north==5,'_C',df$segref)
  df$segref<-ifelse(df$east==2 & df$north==4,'_H',df$segref)
  df$segref<-ifelse(df$east==2 & df$north==5,'_H',df$segref)
  df$segref<-ifelse(df$east==3 & df$north==4,'_H',df$segref)
  df$segref<-ifelse(df$east==3 & df$north==5,'_H',df$segref)
  df$segref<-ifelse(df$east==4 & df$north==4,'_M',df$segref)
  df$segref<-ifelse(df$east==4 & df$north==5,'_M',df$segref)
  df$segref<-ifelse(df$east==5 & df$north==4,'_M',df$segref)
  df$segref<-ifelse(df$east==5 & df$north==5,'_M',df$segref)
  df$segref<-ifelse(df$east==6 & df$north==4,'_S',df$segref)
  df$segref<-ifelse(df$east==6 & df$north==5,'_S',df$segref)
  df$segref<-ifelse(df$east==7 & df$north==4,'_S',df$segref)
  df$segref<-ifelse(df$east==7 & df$north==5,'_S',df$segref)
  df$segref<-ifelse(df$east==8 & df$north==4,'_X',df$segref)
  df$segref<-ifelse(df$east==8 & df$north==5,'_X',df$segref)
  df$segref<-ifelse(df$east==9 & df$north==4,'_X',df$segref)
  df$segref<-ifelse(df$east==9 & df$north==5,'_X',df$segref)
  df$segref<-ifelse(df$east==0 & df$north==6,'_D',df$segref)
  df$segref<-ifelse(df$east==0 & df$north==7,'_D',df$segref)
  df$segref<-ifelse(df$east==1 & df$north==6,'_D',df$segref)
  df$segref<-ifelse(df$east==1 & df$north==7,'_D',df$segref)
  df$segref<-ifelse(df$east==2 & df$north==6,'_I',df$segref)
  df$segref<-ifelse(df$east==2 & df$north==7,'_I',df$segref)
  df$segref<-ifelse(df$east==3 & df$north==6,'_I',df$segref)
  df$segref<-ifelse(df$east==3 & df$north==7,'_I',df$segref)
  df$segref<-ifelse(df$east==4 & df$north==6,'_N',df$segref)
  df$segref<-ifelse(df$east==4 & df$north==7,'_N',df$segref)
  df$segref<-ifelse(df$east==5 & df$north==6,'_N',df$segref)
  df$segref<-ifelse(df$east==5 & df$north==7,'_N',df$segref)
  df$segref<-ifelse(df$east==6 & df$north==6,'_T',df$segref)
  df$segref<-ifelse(df$east==6 & df$north==7,'_T',df$segref)
  df$segref<-ifelse(df$east==7 & df$north==6,'_T',df$segref)
  df$segref<-ifelse(df$east==7 & df$north==7,'_T',df$segref)
  df$segref<-ifelse(df$east==8 & df$north==6,'_Y',df$segref)
  df$segref<-ifelse(df$east==8 & df$north==7,'_Y',df$segref)
  df$segref<-ifelse(df$east==9 & df$north==6,'_Y',df$segref)
  df$segref<-ifelse(df$east==9 & df$north==7,'_Y',df$segref)
  df$segref<-ifelse(df$east==0 & df$north==8,'_E',df$segref)
  df$segref<-ifelse(df$east==0 & df$north==9,'_E',df$segref)
  df$segref<-ifelse(df$east==1 & df$north==8,'_E',df$segref)
  df$segref<-ifelse(df$east==1 & df$north==9,'_E',df$segref)
  df$segref<-ifelse(df$east==2 & df$north==8,'_J',df$segref)
  df$segref<-ifelse(df$east==2 & df$north==9,'_J',df$segref)
  df$segref<-ifelse(df$east==3 & df$north==8,'_J',df$segref)
  df$segref<-ifelse(df$east==3 & df$north==9,'_J',df$segref)
  df$segref<-ifelse(df$east==4 & df$north==8,'_P',df$segref)
  df$segref<-ifelse(df$east==4 & df$north==9,'_P',df$segref)
  df$segref<-ifelse(df$east==5 & df$north==8,'_P',df$segref)
  df$segref<-ifelse(df$east==5 & df$north==9,'_P',df$segref)
  df$segref<-ifelse(df$east==6 & df$north==8,'_U',df$segref)
  df$segref<-ifelse(df$east==6 & df$north==9,'_U',df$segref)
  df$segref<-ifelse(df$east==7 & df$north==8,'_U',df$segref)
  df$segref<-ifelse(df$east==7 & df$north==9,'_U',df$segref)
  df$segref<-ifelse(df$east==8 & df$north==8,'_Z',df$segref)
  df$segref<-ifelse(df$east==8 & df$north==9,'_Z',df$segref)
  df$segref<-ifelse(df$east==9 & df$north==8,'_Z',df$segref)
  df$segref<-ifelse(df$east==9 & df$north==9,'_Z',df$segref)
  df$segref<-paste0(df$let,df$segref)
  return(df)
}


#####################################################################################################################################################
# convert 10km reference to 50km reference -----------------------------------------------------------------------
#####################################################################################################################################################
gridconv10km.to.50km<-function(df,invar) 
  #df = the dataframe to process
  #invar = the name of the variable holding the grid reference
  {
  #which column to process
  invar.index<-which(names(df)== invar)
  #force name to be tenkm to make easier processing
  names(df)[invar.index]<-'tenkm'
  letters<-substr(df$tenkm,1,2)
  east<-as.numeric(substr(df$tenkm,3,3))
  north<-as.numeric(substr(df$tenkm,4,4))
  df$quadref<-NA
  df$quadref<-ifelse(east<=4 & north<=4, paste(letters,'SW',sep=''),df$quadref)
  df$quadref<-ifelse(east<=4 & north>4, paste(letters,'NW',sep=''),df$quadref)
  df$quadref<-ifelse(east>4 & north>4, paste(letters,'NE',sep=''),df$quadref)
  df$quadref<-ifelse(east>4 & north<=4, paste(letters,'SE',sep=''),df$quadref)
  return(df)
}



#####################################################################################################################################################
# convert 1km reference to tetrad reference -----------------------------------------------------------------------
#####################################################################################################################################################
gridconv01km.to.02km<-function(df,invar) 
  #df = the dataframe to process
  #invar = the name of the variable holding the grid reference
  {
  #which column to process
  invar.index<-which(names(df)== invar)
  #force name to be gridref to make easier processing
  names(df)[invar.index]<-'gridref'
  df$let<-substr(df$gridref,1,2)
  df$e10<-substr(df$gridref,3,3)
  df$e1<-substr(df$gridref,4,4)
  df$n10<-substr(df$gridref,5,5)
  df$n1<-substr(df$gridref,6,6)
  df$tet<-'o'
  df$tet<-ifelse(df$e1==0 & df$n1==0,'A',df$tet)
  df$tet<-ifelse(df$e1==0 & df$n1==1,'A',df$tet)
  df$tet<-ifelse(df$e1==1 & df$n1==0,'A',df$tet)
  df$tet<-ifelse(df$e1==1 & df$n1==1,'A',df$tet)
  df$tet<-ifelse(df$e1==2 & df$n1==0,'F',df$tet)
  df$tet<-ifelse(df$e1==2 & df$n1==1,'F',df$tet)
  df$tet<-ifelse(df$e1==3 & df$n1==0,'F',df$tet)
  df$tet<-ifelse(df$e1==3 & df$n1==1,'F',df$tet)
  df$tet<-ifelse(df$e1==4 & df$n1==0,'K',df$tet)
  df$tet<-ifelse(df$e1==4 & df$n1==1,'K',df$tet)
  df$tet<-ifelse(df$e1==5 & df$n1==0,'K',df$tet)
  df$tet<-ifelse(df$e1==5 & df$n1==1,'K',df$tet)
  df$tet<-ifelse(df$e1==6 & df$n1==0,'Q',df$tet)
  df$tet<-ifelse(df$e1==6 & df$n1==1,'Q',df$tet)
  df$tet<-ifelse(df$e1==7 & df$n1==0,'Q',df$tet)
  df$tet<-ifelse(df$e1==7 & df$n1==1,'Q',df$tet)
  df$tet<-ifelse(df$e1==8 & df$n1==0,'V',df$tet)
  df$tet<-ifelse(df$e1==8 & df$n1==1,'V',df$tet)
  df$tet<-ifelse(df$e1==9 & df$n1==0,'V',df$tet)
  df$tet<-ifelse(df$e1==9 & df$n1==1,'V',df$tet)
  df$tet<-ifelse(df$e1==0 & df$n1==2,'B',df$tet)
  df$tet<-ifelse(df$e1==0 & df$n1==3,'B',df$tet)
  df$tet<-ifelse(df$e1==1 & df$n1==2,'B',df$tet)
  df$tet<-ifelse(df$e1==1 & df$n1==3,'B',df$tet)
  df$tet<-ifelse(df$e1==2 & df$n1==2,'G',df$tet)
  df$tet<-ifelse(df$e1==2 & df$n1==3,'G',df$tet)
  df$tet<-ifelse(df$e1==3 & df$n1==2,'G',df$tet)
  df$tet<-ifelse(df$e1==3 & df$n1==3,'G',df$tet)
  df$tet<-ifelse(df$e1==4 & df$n1==2,'L',df$tet)
  df$tet<-ifelse(df$e1==4 & df$n1==3,'L',df$tet)
  df$tet<-ifelse(df$e1==5 & df$n1==2,'L',df$tet)
  df$tet<-ifelse(df$e1==5 & df$n1==3,'L',df$tet)
  df$tet<-ifelse(df$e1==6 & df$n1==2,'R',df$tet)
  df$tet<-ifelse(df$e1==6 & df$n1==3,'R',df$tet)
  df$tet<-ifelse(df$e1==7 & df$n1==2,'R',df$tet)
  df$tet<-ifelse(df$e1==7 & df$n1==3,'R',df$tet)
  df$tet<-ifelse(df$e1==8 & df$n1==2,'W',df$tet)
  df$tet<-ifelse(df$e1==8 & df$n1==3,'W',df$tet)
  df$tet<-ifelse(df$e1==9 & df$n1==2,'W',df$tet)
  df$tet<-ifelse(df$e1==9 & df$n1==3,'W',df$tet)
  df$tet<-ifelse(df$e1==0 & df$n1==4,'C',df$tet)
  df$tet<-ifelse(df$e1==0 & df$n1==5,'C',df$tet)
  df$tet<-ifelse(df$e1==1 & df$n1==4,'C',df$tet)
  df$tet<-ifelse(df$e1==1 & df$n1==5,'C',df$tet)
  df$tet<-ifelse(df$e1==2 & df$n1==4,'H',df$tet)
  df$tet<-ifelse(df$e1==2 & df$n1==5,'H',df$tet)
  df$tet<-ifelse(df$e1==3 & df$n1==4,'H',df$tet)
  df$tet<-ifelse(df$e1==3 & df$n1==5,'H',df$tet)
  df$tet<-ifelse(df$e1==4 & df$n1==4,'M',df$tet)
  df$tet<-ifelse(df$e1==4 & df$n1==5,'M',df$tet)
  df$tet<-ifelse(df$e1==5 & df$n1==4,'M',df$tet)
  df$tet<-ifelse(df$e1==5 & df$n1==5,'M',df$tet)
  df$tet<-ifelse(df$e1==6 & df$n1==4,'S',df$tet)
  df$tet<-ifelse(df$e1==6 & df$n1==5,'S',df$tet)
  df$tet<-ifelse(df$e1==7 & df$n1==4,'S',df$tet)
  df$tet<-ifelse(df$e1==7 & df$n1==5,'S',df$tet)
  df$tet<-ifelse(df$e1==8 & df$n1==4,'X',df$tet)
  df$tet<-ifelse(df$e1==8 & df$n1==5,'X',df$tet)
  df$tet<-ifelse(df$e1==9 & df$n1==4,'X',df$tet)
  df$tet<-ifelse(df$e1==9 & df$n1==5,'X',df$tet)
  df$tet<-ifelse(df$e1==0 & df$n1==6,'D',df$tet)
  df$tet<-ifelse(df$e1==0 & df$n1==7,'D',df$tet)
  df$tet<-ifelse(df$e1==1 & df$n1==6,'D',df$tet)
  df$tet<-ifelse(df$e1==1 & df$n1==7,'D',df$tet)
  df$tet<-ifelse(df$e1==2 & df$n1==6,'I',df$tet)
  df$tet<-ifelse(df$e1==2 & df$n1==7,'I',df$tet)
  df$tet<-ifelse(df$e1==3 & df$n1==6,'I',df$tet)
  df$tet<-ifelse(df$e1==3 & df$n1==7,'I',df$tet)
  df$tet<-ifelse(df$e1==4 & df$n1==6,'N',df$tet)
  df$tet<-ifelse(df$e1==4 & df$n1==7,'N',df$tet)
  df$tet<-ifelse(df$e1==5 & df$n1==6,'N',df$tet)
  df$tet<-ifelse(df$e1==5 & df$n1==7,'N',df$tet)
  df$tet<-ifelse(df$e1==6 & df$n1==6,'T',df$tet)
  df$tet<-ifelse(df$e1==6 & df$n1==7,'T',df$tet)
  df$tet<-ifelse(df$e1==7 & df$n1==6,'T',df$tet)
  df$tet<-ifelse(df$e1==7 & df$n1==7,'T',df$tet)
  df$tet<-ifelse(df$e1==8 & df$n1==6,'Y',df$tet)
  df$tet<-ifelse(df$e1==8 & df$n1==7,'Y',df$tet)
  df$tet<-ifelse(df$e1==9 & df$n1==6,'Y',df$tet)
  df$tet<-ifelse(df$e1==9 & df$n1==7,'Y',df$tet)
  df$tet<-ifelse(df$e1==0 & df$n1==8,'E',df$tet)
  df$tet<-ifelse(df$e1==0 & df$n1==9,'E',df$tet)
  df$tet<-ifelse(df$e1==1 & df$n1==8,'E',df$tet)
  df$tet<-ifelse(df$e1==1 & df$n1==9,'E',df$tet)
  df$tet<-ifelse(df$e1==2 & df$n1==8,'J',df$tet)
  df$tet<-ifelse(df$e1==2 & df$n1==9,'J',df$tet)
  df$tet<-ifelse(df$e1==3 & df$n1==8,'J',df$tet)
  df$tet<-ifelse(df$e1==3 & df$n1==9,'J',df$tet)
  df$tet<-ifelse(df$e1==4 & df$n1==8,'P',df$tet)
  df$tet<-ifelse(df$e1==4 & df$n1==9,'P',df$tet)
  df$tet<-ifelse(df$e1==5 & df$n1==8,'P',df$tet)
  df$tet<-ifelse(df$e1==5 & df$n1==9,'P',df$tet)
  df$tet<-ifelse(df$e1==6 & df$n1==8,'U',df$tet)
  df$tet<-ifelse(df$e1==6 & df$n1==9,'U',df$tet)
  df$tet<-ifelse(df$e1==7 & df$n1==8,'U',df$tet)
  df$tet<-ifelse(df$e1==7 & df$n1==9,'U',df$tet)
  df$tet<-ifelse(df$e1==8 & df$n1==8,'Z',df$tet)
  df$tet<-ifelse(df$e1==8 & df$n1==9,'Z',df$tet)
  df$tet<-ifelse(df$e1==9 & df$n1==8,'Z',df$tet)
  df$tet<-ifelse(df$e1==9 & df$n1==9,'Z',df$tet)
  df$tetrad_id<-paste(df$let,df$e10,df$n10,df$tet,sep='')
  return(df)
}
